name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.ACRID }}
        # Container registry password
        password: ${{ secrets.ACRKEY }}
        # Container registry server url
        login-server: mynodeapicontainerregistry.azurecr.io
        
    - name: Build the Docker image
      run: |
            docker build . --file Dockerfile --tag my-image-name:$(date +%s)
            docker push mynodeapicontainerregistry.azurecr.io/appdb:${{ github.sha }}
