name: Generate and save SSH key

on:
  workflow_dispatch:

jobs:
  generate-ssh-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate SSH key pair
        run: |
          ssh-keygen -t rsa -b 4096 -C "shekhawatajit@hotmail.com" -f ssh_key -q -N ""
          echo "::set-output name=private_key::$(cat mykey)"
