name: Generate and save SSH key

on:
  workflow_dispatch:

jobs:
  generate-ssh-key:
    runs-on: ubuntu-latest

    steps:
      - name: Set output
        uses: actions/core@v2
        with:
          id: myOutput
          value: "hello world"
