name: Generate and save SSH key

on:
  workflow_dispatch:

jobs:
  generate-ssh-key:
    runs-on: ubuntu-latest

    steps:
      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -b 4096 -C "shekhawatajit@hotmail.com" -f ssh_key -q -N ""
          cat ssh_key.pub
        id: ssh-key

      - name: Store private key as GitHub secret
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Use the public key
        run: |
          echo "Public key value: ${{ steps.ssh-key.outputs.public_key }}"
        env:
          PUBLIC_KEY: ${{ steps.ssh-key.outputs.public_key }}
